{
 "title": "Jam Dashboard",
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Total people minutes in rooms",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum_over_time(jam_users_active[10y])/4"
    }
   ]
  },
  {
   "title": "People minutes in rooms (24h rolling sum)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum_over_time(jam_users_active[1d])/4"
    }
   ]
  },
  {
   "title": "Active Users (hourly stats)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(jam_users_active[1h])",
     "legendFormat": "avg"
    },
    {
     "expr": "min_over_time(jam_users_active[1h])",
     "legendFormat": "min"
    },
    {
     "expr": "max_over_time(jam_users_active[1h])",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Active Users",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jam_users_active" }
   ]
  },
  {
   "title": "Total Rooms",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jam_rooms_total" }
   ]
  },
  {
   "title": "Day by Day increase of rooms",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "increase(jam_rooms_total[1d])" }
   ]
  },
  {
   "title": "Total Identities",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jam_identities_total" }
   ]
  },
  {
   "title": "Day by Day increase of identities",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(jam_identities_total[1d])"
    }
   ]
  }
 ]
}